name: Brakeman Scan
on:
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:
jobs:
  Scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Brakeman code scanning
        uses: standardnotes/brakeman-action@v1.0.0
        with:
          options: "--color -q"
